# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
        
  DeployDev:
    name: deploy on dev envoirment
    ##if: github.event.name == 'push'
    needs: [build]
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    environment: 
      name: dev
    
     # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
    # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo "welcome to Dev envoirment"
        
        
  DeployStaging:
    name: deploy on Stage envoirment
   ## if: github.event.ref == 'refs/heads/main'
    needs: [build ,DeployDev]

    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    environment: 
      name: stage
    
     # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
    # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo "welcome to Stage envoirment"
        
        
  DeployProd:
    name: deploy on Prod envoirment
    needs: [build ,DeployDev,DeployStaging]
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    environment: 
      name: prod
    
     # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
    # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo "welcome to prod envoirment"
        
  
      


    

